<a href="https://colab.research.google.com/github/abolfazlaghdaee/LLM_journey/blob/main/Project01_DS04_S01_NLTK_SpaCy_RezaShokrzad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📜 Project: Job Description Analyzer – Extracting Required Skills from Job Postings

## 📌 Objective
Use spaCy’s Named Entity Recognition (NER) and NLTK preprocessing to extract and categorize required skills from job descriptions. The goal is to identify trends in job requirements and analyze the most in-demand skills across industries.

## 🛠️ Project Steps & Instructions

In [1]:
#📥 Download the Dataset
!wget https://raw.githubusercontent.com/binoydutt/Resume-Job-Description-Matching/refs/heads/master/data.csv

--2025-03-19 12:00:13--  https://raw.githubusercontent.com/binoydutt/Resume-Job-Description-Matching/refs/heads/master/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 646072 (631K) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>] 630.93K  2.95MB/s    in 0.2s

2025-03-19 12:00:17 (2.95 MB/s) - ‘data.csv’ saved [646072/646072]

### Step 1: Load the Dataset
#### 📌 Dataset: A provided CSV file containing job descriptions from different industries (IT, Healthcare, Finance, Marketing, etc.).

1. Download the dataset (link below).
2. Load it into Python using Pandas.
3. View the first few rows to understand its structure.

In [9]:
# your code here
import pandas as pd

#section2
df = pd.read_csv('/content/data.csv')

#section3
df.head()

,Unnamed: 0,company,position,url,location,headquaters,employees,founded,industry,Job Description
0,1,Visual BI Solutions Inc,Graduate Intern (Summer 2017) - SAP BI / Big D...,https://www.glassdoor.com/partner/jobListing.h...,"Plano, TX","Plano, TX",51 to 200 employees,2010,Information Technology,"Location: Plano, TX or Oklahoma City, OK Dura..."
1,2,Jobvertise,Digital Marketing Manager,https://www.glassdoor.com/partner/jobListing.h...,"Dallas, TX","Berlin, Germany",1 to 50 employees,2011,Unknown,The Digital Marketing Manager is the front li...
2,3,Santander Consumer USA,"Manager, Pricing Management Information Systems",https://www.glassdoor.com/partner/jobListing.h...,"Dallas, TX","Dallas, TX",5001 to 10000 employees,1995,Finance,Summary of Responsibilities:The Manager Prici...
3,4,Federal Reserve Bank of Dallas,Treasury Services Analyst Internship,https://www.glassdoor.com/partner/jobListing.h...,"Dallas, TX","Dallas, TX",1001 to 5000 employees,1914,Finance,ORGANIZATIONAL SUMMARY: As part of the nati...
4,5,Aviall,"Intern, Sales Analyst",https://www.glassdoor.com/partner/jobListing.h...,"Dallas, TX","Dallas, TX",1001 to 5000 employees,Boeing,Subsidiary or Business Segment,Aviall is the world's largest provider of n...

### Step 2: Preprocessing the Job Descriptions
#### 📌 Goal: Clean the text by removing stopwords, punctuation, and unnecessary characters.

1. Use NLTK to tokenize the descriptions.
2. Remove stopwords and special characters.
3. Convert text to lowercase for consistency.

In [3]:
# your code here
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from nltk) (4.67.1)

In [10]:
import nltk

nltk.download('punkt_tab')
nltk.download('stopwords')

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
stopwords = set(stopwords.words('english'))

#section1
df['Tokenized Job Description'] = df['Job Description'].map(word_tokenize)


df['Tokenized Job Description']

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

0      [Location, :, Plano, ,, TX, or, Oklahoma, City...
1      [The, Digital, Marketing, Manager, is, the, fr...
2      [Summary, of, Responsibilities, :, The, Manage...
3      [ORGANIZATIONAL, SUMMARY, :, As, part, of, the...
4      [Aviall, is, the, world, 's, largest, provider...
                             ...
152    [Real-world, Experience, ., Life-long, Connect...
153    [The, Internship, Program, Our, paid, internsh...
154    [Are, you, an, analytical, thinker, with, a, p...
155    [The, Internship, Program, Our, paid, internsh...
156    [Do, you, want, to, jump, start, your, career,...
Name: Tokenized Job Description, Length: 157, dtype: object

In [11]:
#section2 and section3

def clear(words):

  clear_token = [word.lower() for word in words if word.isalnum() and word.lower() not in stopwords]

  return clear_token



df['Tokenized Job Description'] = df['Tokenized Job Description'].map(clear)

df['Tokenized Job Description']

0      [location, plano, tx, oklahoma, city, ok, dura...
1      [digital, marketing, manager, front, line, pat...
2      [summary, responsibilities, manager, pricing, ...
3      [organizational, summary, part, nation, centra...
4      [aviall, world, largest, provider, new, aviati...
                             ...
152    [experience, connections, intern, seasoned, he...
153    [internship, program, paid, internship, progra...
154    [analytical, thinker, passion, actuarial, scie...
155    [internship, program, paid, internship, progra...
156    [want, jump, start, career, take, business, sk...
Name: Tokenized Job Description, Length: 157, dtype: object

### Step 3: Extract Skills Using Named Entity Recognition (NER)
#### 📌 Goal: Use spaCy’s built-in NER to detect and extract skills from job descriptions.

1. Load spaCy’s English model.
2. Use NER to identify important keywords.
3. Extract words related to technical skills, tools, and expertise.

In [33]:
# your code here

#section1
!pip install spacy
import spacy

nlp = spacy.load('en_core_web_sm')


#section 2 & 3

def ner(data):

  text = ' '.join(data)

  doc = nlp(text)

  extract_words = []

  for word in doc.ents:
    if word.label_ in ["ORG","PRODUCT", "SKILL"]:
      extract_words.append(word.text)



  return extract_words




df['extract_words'] = df['Tokenized Job Description'].map(ner)

Requirement already satisfied: spacy in /usr/local/lib/python3.11/dist-packages (3.8.4)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.11/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (1.0.12)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.11/dist-packages (from spacy) (3.0.9)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.11/dist-packages (from spacy) (8.3.4)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.11/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (0.15.2)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.11/dist-packages (from spacy) (2.10.6)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from spacy) (75.1.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (24.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from spacy) (3.5.0)
Requirement already satisfied: language-data>=1.2 in /usr/local/lib/python3.11/dist-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.27.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.11/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.1.31)
Requirement already satisfied: blis<1.3.0,>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.2.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.21.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.11/dist-packages (from weasel<0.5.0,>=0.1.0->spacy) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->spacy) (3.0.2)
Requirement already satisfied: marisa-trie>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy) (1.2.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.18.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy) (1.17.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)

In [34]:
df[['Job Description','Tokenized Job Description', 'extract_words']]

,Job Description,Tokenized Job Description,extract_words
0,"Location: Plano, TX or Oklahoma City, OK Dura...","[location, plano, tx, oklahoma, city, ok, dura...",[gpa scores]
1,The Digital Marketing Manager is the front li...,"[digital, marketing, manager, front, line, pat...",[digital]
2,Summary of Responsibilities:The Manager Prici...,"[summary, responsibilities, manager, pricing, ...",[]
3,ORGANIZATIONAL SUMMARY: As part of the nati...,"[organizational, summary, part, nation, centra...","[federal reserve bank, dallas treasury service..."
4,Aviall is the world's largest provider of n...,"[aviall, world, largest, provider, new, aviati...",[]
...,...,...,...
152,Real-world Experience. Life-long Connections....,"[experience, connections, intern, seasoned, he...",[]
153,The Internship Program Our paid internship p...,"[internship, program, paid, internship, progra...",[tx department]
154,Are you an analytical thinker with a passion ...,"[analytical, thinker, passion, actuarial, scie...","[deloitte university, deloitte university, del..."
155,The Internship Program Our paid internship p...,"[internship, program, paid, internship, progra...","[tx department name ag, ag, ag, microsoft]"
156,Do you want to jump start your career and tak...,"[want, jump, start, career, take, business, sk...",[deloitte]

### Step 4: Identify the Most In-Demand Skills
#### 📌 Goal: Count the most frequently mentioned skills in job descriptions.

1. Create a word frequency distribution of extracted skills.
2. Identify the top 10 most required skills.

In [25]:
# your code here
from collections import Counter


skills =[]
for i in df['extract_words']:
  skills.extend(i)



Counter(skills).most_common(10)

[('microsoft', 46),
 ('ibm', 31),
 ('microsoft office', 23),
 ('deloitte', 20),
 ('texas usa', 7),
 ('deloitte university', 7),
 ('grant thornton international ltd one', 6),
 ('phoenix house', 6),
 ('google', 4),
 ('microsoft sql', 4)]

### Step 5: Categorize Skills by Industry
#### 📌 Goal: Compare the most in-demand skills across different industries.

1. Group job descriptions by industry.
2. Extract and analyze skills for each industry.
3. Compare IT vs. Marketing vs. Healthcare, etc..

In [29]:
# your code here
df.dropna(subset=["industry", "Job Description"])
df["industry"].value_counts()

industry
Business Services                            23
Information Technology                       21
Accounting & Legal                           20
Finance                                      17
Media                                        12
Manufacturing                                11
Health Care                                  10
Unknown                                       8
Subsidiary or Business Segment                8
Insurance                                     5
Arts, Entertainment & Recreation              4
Retail                                        3
Aerospace & Defense                           2
$500 million to $1 billion (USD) per year     2
Travel & Tourism                              1
Non-Profit                                    1
Unknown / Non-Applicable per year             1
Real Estate                                   1
Transportation & Logistics                    1
Company - Public                              1
Mining & Metals                               1
Construction, Repair & Maintenance            1
Name: count, dtype: int64

In [35]:
dic_skills = {}

for industry in df["industry"].unique():
  df_industry = df[df["industry"] == industry]['extract_words']
  skills = []
  for i in df_industry:
    skills.extend(i)
  dic_skills[industry] = Counter(skills).most_common(10)

In [42]:
for industry, skills in dic_skills.items():
    print(f"Top skills in {industry}:")
    print(skills)
    print("-" * 50)

Top skills in Information Technology:
[('microsoft', 15), ('texas usa', 6), ('microsoft sql', 4), ('microsoft office', 2), ('sap academy', 2), ('sap academy presales successfully', 2), ('sap academy presales sap presales academy', 2), ('sap academy presales looks', 2), ('metadata management data integration technologies hadoop', 2), ('gpa scores', 1)]
--------------------------------------------------
Top skills in Unknown:
[('microsoft', 2), ('digital', 1), ('google', 1), ('401k', 1), ('metadata management data integration technologies hadoop', 1)]
--------------------------------------------------
Top skills in Finance:
[('federal reserve bank', 3), ('dallas treasury services department regularly apply analytical problem', 3), ('microsoft', 3), ('new york stock exchange', 3), ('microsoft office', 2), ('google', 2), ('hris research', 1), ('ibm', 1), ('north america', 1), ('united states america', 1)]
--------------------------------------------------
Top skills in Subsidiary or Business Segment:
[('microsoft office', 6), ('gpa education college coursework', 2)]
--------------------------------------------------
Top skills in Business Services:
[('ibm', 30), ('microsoft', 7), ('environmentstrong prioritization skillsstrong', 2), ('dmv', 2), ('epsilonmktg alliance', 2), ('cms', 1), ('irving us', 1), ('texas usa', 1), ('ceb nyse ceb', 1), ('department ceb corporate department', 1)]
--------------------------------------------------
Top skills in Accounting & Legal:
[('deloitte', 18), ('deloitte university', 7), ('grant thornton international ltd one', 6), ('microsoft', 3), ('txmc19652', 2), ('deloitte touche', 2), ('microsoft office', 2), ('irs', 2), ('gpa travel required skill requirements', 1), ('cia', 1)]
--------------------------------------------------
Top skills in Health Care:
[('phoenix house', 6), ('texas phoenix house', 1), ('phoenix house facebo phoenix house', 1), ('microsoft', 1), ('microsoft visio', 1)]
--------------------------------------------------
Top skills in Media:
[('microsoft office', 11), ('microsoft', 1)]
--------------------------------------------------
Top skills in nan:
[]
--------------------------------------------------
Top skills in Non-Profit:
[('intern research development', 1), ('american stroke association', 1), ('united states', 1)]
--------------------------------------------------
Top skills in Arts, Entertainment & Recreation:
[('microsoft', 4), ('android', 2)]
--------------------------------------------------
Top skills in $500 million to $1 billion (USD) per year:
[]
--------------------------------------------------
Top skills in Manufacturing:
[('microsoft', 4), ('ag', 4), ('tx department name ag', 2), ('tx department', 2), ('gpa', 1), ('motion flowserve flowserve', 1), ('united states america req', 1)]
--------------------------------------------------
Top skills in Travel & Tourism:
[('microsoft', 1)]
--------------------------------------------------
Top skills in Insurance:
[('blue cross blue shield', 2), ('gpa greater', 2), ('sas sql data analysis descriptive', 2), ('blue cross blue plans', 2), ('gpa scale', 2), ('microsoft', 2)]
--------------------------------------------------
Top skills in Aerospace & Defense:
[('northrop', 1), ('jsp', 1), ('sql r oracle sql server relational', 1)]
--------------------------------------------------
Top skills in Unknown / Non-Applicable per year:
[('microsoft visio', 1), ('cms', 1)]
--------------------------------------------------
Top skills in Retail:
[('digital marketing', 1), ('ford', 1), ('digital internship penney company', 1), ('jcpenneys desktop mobile application', 1), ('android', 1)]
--------------------------------------------------
Top skills in Real Estate:
[('microsoft', 1)]
--------------------------------------------------
Top skills in Transportation & Logistics:
[('microsoft', 1)]
--------------------------------------------------
Top skills in Company - Public:
[('gm', 4)]
--------------------------------------------------
Top skills in Mining & Metals:
[('united states', 1), ('habitat council', 1)]
--------------------------------------------------
Top skills in Construction, Repair & Maintenance:
[('united states', 1), ('habitat council', 1)]
--------------------------------------------------

In [50]:
# It , Marketing(skills in Business Services), Health care
print(dic_skills['Information Technology'])

print(50*'-')

print(dic_skills['Business Services'])

print(50*'-')

dic_skills['Health Care']

[('microsoft', 15), ('texas usa', 6), ('microsoft sql', 4), ('microsoft office', 2), ('sap academy', 2), ('sap academy presales successfully', 2), ('sap academy presales sap presales academy', 2), ('sap academy presales looks', 2), ('metadata management data integration technologies hadoop', 2), ('gpa scores', 1)]
--------------------------------------------------
[('ibm', 30), ('microsoft', 7), ('environmentstrong prioritization skillsstrong', 2), ('dmv', 2), ('epsilonmktg alliance', 2), ('cms', 1), ('irving us', 1), ('texas usa', 1), ('ceb nyse ceb', 1), ('department ceb corporate department', 1)]
--------------------------------------------------

[('phoenix house', 6),
 ('texas phoenix house', 1),
 ('phoenix house facebo phoenix house', 1),
 ('microsoft', 1),
 ('microsoft visio', 1)]